'use strict';

// Alias exports to a their normalized format Mocha#reporter to prevent a need
// for dynamic (try/catch) requires, which Browserify doesn't handle.
import Base from './base.js';
import Dot from './dot.js';
import Doc from './doc.js';
import TAP from './tap.js';
import JSONReporter from './json.js';
import HTML from './html.js';
import List from './list.js';
import Min from './min.js';
import Spec from './spec.js';
import Nyan from './nyan.js';
import XUnit from './xunit.js';
import Markdown from './markdown.js';
import Progress from './progress.js';
import Landing from './landing.js';
import JSONStream from './json-stream.js';

export const base = Base;
export const Base = Base;
export const dot = Dot;
export const Dot = Dot;
export const doc = Doc;
export const Doc = Doc;
export const tap = TAP;
export const TAP = TAP;
export const json = JSONReporter;
export const JSON = JSONReporter;
export const html = HTML;
export const HTML = HTML;
export const list = List;
export const List = List;
export const min = Min;
export const Min = Min;
export const spec = Spec;
export const Spec = Spec;
export const nyan = Nyan;
export const Nyan = Nyan;
export const xunit = XUnit;
export const XUnit = XUnit;
export const markdown = Markdown;
export const Markdown = Markdown;
export const progress = Progress;
export const Progress = Progress;
export const landing = Landing;
export const Landing = Landing;
export {JSONStream};
export {JSONStream as 'json-stream'};
